//@version=4



// -------------------------------------------------------------------------- //



study(title="BB", shorttitle="BB", overlay=true)



// -------------------------------------------------------------------------- //



bbl = input(title="BB Length", type=input.integer, defval=21,  minval=1,   step=1  )
bbs = input(title="BB Stddev", type=input.float,   defval=2.0, minval=0.1, step=0.1)



// -------------------------------------------------------------------------- //



new_bbi(src, bbl, bbs) =>
    std = bbs * stdev(src, bbl)

    bbm = sma(src, bbl)
    bbu = bbm + std
    bbd = bbm - std

    [bbu, bbm, bbd]



// -------------------------------------------------------------------------- //



[bbu, bbm, bbd] = new_bbi(close, bbl, bbs)

plot(bbu, "BB Up",     color=color.gray)
plot(bbm, "BB Median", color=color.gray)
plot(bbd, "BB Down",   color=color.gray)
