//@version=4



// -------------------------------------------------------------------------- //



study(title="HPI", shorttitle="HPI", overlay=true)



// -------------------------------------------------------------------------- //



hrb = input(title="HPI Recent Bar", type=input.integer, defval=50, minval=1, step=1)



// new_crb returns true if the current bar is red, that is, the current open
// price is higher than the current close price. This signals a local downward
// movement. Here crb means current red bar.
new_crb() =>
    open > close

// new_hpi returns a high price indicator for the most recent bars since hrb.
// Here hpi means high price indicator.
new_hpi(hrb) =>
    highest(open, hrb) == open and new_crb()



// -------------------------------------------------------------------------- //



plotshape(new_hpi(hrb), text="HPI", location=location.abovebar, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white, transp=0)
