// new_hps finds the highest price since bar. Here src is the source price e.g.
// close. Here bar means recent bars. Here hps means highest price.
new_hps(src, bar) =>
    hps = src[0]

    for i = 0 to bar
        hps := src[i] > hps ? src[i] : hps

    hps

// new_hpi returns a high price indicator based on the recent bars and their
// associated price change. Here hpi means high price indicator.
//
//     plotshape(new_hpi(), text="HPI", ...)
//
new_hpi() =>
    // Define the n recent bars to look back. Here bar means recent bars.
    bar = 100
    // Define the price change to consider in the past. Here prh means price
    // change.
    prh = 0.001

    (new_per(close, new_hps(close, bar)) - 100) > prh ? na : true
