//@version=4



// -------------------------------------------------------------------------- //



study(title="Test", shorttitle="Test", overlay=true)



// -------------------------------------------------------------------------- //



hrb = input(title="HPI Recent Bar",   type=input.integer, defval = 50,   minval = 1,     step=1    )
hpc = input(title="HPI Price Change", type=input.float,   defval = 0.05, minval = 0.001, step=0.001)



// new_per calculates the percentage of a fraction based on the given absolute
// value.
//
//     new_per(100, 5) => 5
//
new_per(abs, fra) =>
    fra * 100 / abs

// new_hps finds the highest price since reb. Here src is the source price e.g.
// close. Here reb means recent bars. Here hps means high price since.
new_hps(src, reb) =>
    lcp = src[0]

    for i = 0 to reb
        lcp := src[i] > lcp ? src[i] : lcp

    lcp

// new_hpb returns a high price indicator for the current bar, based on the
// recent bars and their associated price change. Here hpb means high price
// bar.
new_hpb(src, hrb, hpc) =>
    (new_per(src, new_hps(src, hrb)) - 100) > hpc ? na : true

// new_hpi returns a high price indicator for three or four high price signals
// in a row as calculated by new_hpb. Here hpi means high price indicator.
new_hpi(src, hrb, hpc) =>
    hpb = new_hpb(src, hrb, hpc)

    thr = hpb[0] and hpb[1] and hpb[2]
    fou = hpb[0] and hpb[1] and hpb[2] and hpb[3]

    thr or fou



// -------------------------------------------------------------------------- //



rsl = input(title="RSI Length", type=input.integer, defval = 21, minval = 1, step=1)
rsp = input(title="RSI Pivot",  type=input.integer, defval = 60, minval = 1, step=1)



// new_crb returns true if the current bar is red, that is, the current open
// price is higher than the current close price. This signals a local downward
// movement. Here crb means current red bar.
new_crb() =>
    open > close

// new_hpb returns the relative strength indicator for the current bar, based on
// the running moving average. Here rsb means relative strength bar.
new_rsb(src, rsl) =>
    upw = rma( max(change(src), 0), rsl)
    dow = rma(-min(change(src), 0), rsl)

    dow == 0 ? 100 : upw == 0 ? 0 : 100 - (100 / (1 + upw / dow))

// new_rsi returns the relative strength indicator for overbought price peaks.
// If the RSI band crosses under the RSI turning point given by rsp then new_rsi
// returns true.
new_rsi(src, rsl, rsp) =>
    new_rsb(src, rsl)[1] > rsp and new_rsb(src, rsl)[0] < rsp



// -------------------------------------------------------------------------- //


// new short trend indicator
new_sti() =>
    hpi = new_hpi(close, hrb, hpc)
    rsi = new_rsi(close, rsl, rsp)

    fir = rsi[0]
    sec = hpi[1]

    fir and sec



plotshape(new_sti(), text="SHORT", location=location.abovebar, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white, transp=0)
