//@version=4



study("High Price", shorttitle="High Price", overlay=true)



// new_per calculates the percentage of a fraction based on the given absolute
// value.
//
//     new_per(100, 5) => 5
//
new_per(abs, fra) =>
    fra * 100 / abs

// new_hps finds the highest price since reb. Here src is the source price e.g.
// close. Here reb means recent bars. Here hps means high price since.
new_hps(src, reb) =>
    lcp = src[0]

    for i = 0 to reb
        lcp := src[i] > lcp ? src[i] : lcp

    lcp

// new_hpb returns a high price indicator for the current bar, based on the
// recent bars and their associated price change. Here hpb means high price
// bar.
new_hpb(src) =>
    // Define the n recent bars to look back. Here reb means recent bars.
    reb = 100
    // Define the price change to consider in the past. Here prh means price
    // change.
    prh = 0.001

    (new_per(src, new_hps(src, reb)) - 100) > prh ? na : true

// new_hpi returns a high price indicator for two isolated high price
// indications in a row as calculated by new_hpb. Here hpi means high price
// indicator.
//
//     ... L H H L ...
//
new_hpi(src) =>
    not new_hpb(src)[0] and new_hpb(src)[1] and new_hpb(src)[2] and not new_hpb(src)[3]


plotshape(new_hpi(close), text="HPI", title="Indicator", location=location.abovebar, style=shape.labeldown, size=size.tiny, color=color.red, textcolor=color.white, transp=0)
